### ISSUE TITLE
Data quality check on PRP data sync API for Partner

### ISSUE THREAD

**Issue by n1207n** [unicef/etools#1251]
Hey @robertavram,

Staging data sync Partner API for PRP seems to return a lot of Partner objects that have lots of `null` values. I just wanted to make sure if this is not API issue or bad data. If the API is functioning correctly then, please close this Github issue ;)

However if API is not returning correct data or missing some data then, let me know if PRP needs to make some changes.

cc'ing @chachra

**Comment by robertavram** [comment]
Hey Silin, I'll check, thanks for the heads up!

**Comment by robertavram** [comment]
@n1207n it's all good.. the null values are normal.

@chachra closing this.. let me know if any other issues
