### ISSUE TITLE
Move maps to (new) etools-dash polymer frontend app

### ISSUE THREAD

**Issue by chachra** [unicef/etools#210]
Future goal would be for it to have other functionality / elements in it as well.

Current goal would be for it to have the same functionality as http://etools_domain/map/

Use this template for the new codebase: https://github.com/unicef-polymer/etools-frontend-template

**Comment by chachra** [comment]
Relevant links / places in the code:

https://github.com/unicef/etools/tree/master/frontend_build

https://github.com/unicef/etools/blob/0d575580dbccee003f351e36687001979f93f1cc/EquiTrack/EquiTrack/urls.py#L118

https://github.com/unicef/etools/blob/0d575580dbccee003f351e36687001979f93f1cc/EquiTrack/EquiTrack/views.py#L163

**Comment by chachra** [comment]
CmtDashboardView extends MapView as well.

**Comment by chachra** [comment]
@robertavram please create a new repo "etools-dash" for @n1207n . Thanks.

**Comment by robertavram** [comment]
etools-dash created,

stories related will be handled there.
