### ISSUE TITLE
Don't use LocMemCache as caching config in production

### ISSUE THREAD

**Issue by chachra** [unicef/etools#216]
```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
```
Doesn't seem like its overriden in prod config? This poses issues with eTag caching etc. we've implemented and marking the cache as dirty.

Instead should use django-redish-cache

**Comment by n1207n** [comment]
PR for this issue is closed. [https://github.com/unicef/etools/pull/232](url)
