### ISSUE TITLE
Upgrade DRF to 3.5.X

### ISSUE THREAD

**Issue by chachra** [unicef/etools#219]
Depends on #215 of course, but opening separate one here since it'll take some effort from current DRF version being used.

**Comment by chachra** [comment]
@n1207n can you make sure all tests are running in project george branch?

**Comment by n1207n** [comment]
project-george-package-updates branch has the DRF 3.5 version now. Django unit tests are fixed as well.

**Comment by caktus-philip** [comment]
Current version in eTools is 3.5.3 so it looks like this was implemented.
