### ISSUE TITLE
Integrate etools-dashboard so that dashboard and all subnavs are using it.

### ISSUE THREAD

**Issue by chachra** [unicef/etools#220]
To be consistent with the polymer template / interface.

Will affect interfaces like: homepage and dashboards etc.

Currently looks like this (header / side-nav), which is different than the material blue themed ui in https://github.com/unicef-polymer/etools-frontend-template

CC @ntrncic @robertavram 

<img width="1436" alt="etools" src="https://cloud.githubusercontent.com/assets/73096/20075899/2e585538-a504-11e6-93cd-e9c44680f68f.png">

**Comment by robertavram** [comment]
this is going to be addressed by etools-dashboard...

**Comment by domdinicola** [comment]
@drzackyll do we have this?
