### ISSUE TITLE
Move from hstore to JSON postgres field

### ISSUE THREAD

**Issue by chachra** [unicef/etools#235]
https://github.com/unicef/etools/blob/44e3879ec36c3657bb004e5129720baf5678de2d/EquiTrack/partners/models.py#L1213 - seems like only usage of it. Do a schema migration, data migration, remove hstore field.

**Comment by n1207n** [comment]
Delayed until squash migration is done and merged.

**Comment by caktus-philip** [comment]
Dup of #908
