### ISSUE TITLE
Do a count of tables on each db schema using prod data

### ISSUE THREAD

**Issue by chachra** [unicef/etools#238]
Document schemas that were inconsistent with others....

**Comment by ntrncic** [comment]
gets a count of tables in each schema
select schemaname, COUNT(*) from  pg_stat_user_tables GROUP BY schemaname ORDER BY count;

**Comment by robertavram** [comment]
it seems like this has been done.. conclusion is: we have crap migrations on some business areas... opening another issue to clean up. #257
