### ISSUE TITLE
Activity stream for changes made by users along with the exact data they changed

### ISSUE THREAD

**Issue by chachra** [unicef/etools#239]
Eg. User X approved Trip Y on date Z - changed made:
field 3: a to b
field 6: c to d
etc.

Need an API then for these as well. Can this be done somewhat generically where possible?

External libs:
https://github.com/Atomidata/django-audit-log
https://github.com/justquick/django-activity-stream

**Comment by robertavram** [comment]
in goes: user, old object, new object -> [store changes, user, timestamp, a serialized version of the old obj(snapshot)]

**Comment by n1207n** [comment]
@robertavram In order to store custom data for activity stream, we need to re-introduce `django-jsonfield` package :(

Just for the heads-up.

**Comment by robertavram** [comment]
@n1207n can;t we use this:
https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield

we've updated to 1.9 jsonfield is included

**Comment by n1207n** [comment]
It's a hard requirement for django activity stream. It relies on that package.

**Comment by robertavram** [comment]
@n1207n uhhhh :( I see they have a couple of PRs open for this fix... comment in the requirements to keep an eye out for updates.

**Comment by n1207n** [comment]
@robertavram Cool. I'll put a comment in the requirements. ;)

**Comment by caktus-philip** [comment]
`django-activity-stream` integrated and activity is available via URLs.
