### ISSUE TITLE
Partner Staff Member API

### ISSUE THREAD

**Issue by ntrncic** [unicef/etools#250]
Change PartnerStaffMembersViewSet and PartnerStaffMemberPropertiesView to a View with custom methods for get, post, patch, delete
Change the permissions according to requirements doc
Be able to list staff memebers per partner  `partner/pk/staff-members`
Get one staff member `/staff-members/pk`
For save validations and creating users refer to PArtnerStaffMemberForm and PartnerStaffMember model. There are post save signals for activating and de-activating users. Do not send a response until signal is done.

**Comment by robertavram** [comment]
@ntrncic we don't need to be able to list all partner-staff-members. please update the ask.

**Comment by ilcsik** [comment]
Guys in regard of AuthorizedOfficers list on Agreement.  

- AuthorizedOfficers are created on Agreements save from the PartnerStaffMember that is added newly to the Agreement, so create is covered by that. 

- On the Agreement list serializer, we have "authorized_officers" related name as a set of IDs 

The requirements sheet says its a multiselect dropdown, so I think this is not enough. How should this work in regards of UI?

1, How do we suppose to add new AuthorizedOfficer instances? By a separate API call for AuthorizedOfficer (for eg like github assignees)? Or sending in a list of PartnerStaffMember IDs to the Agreement detail and handling it with custom save method (creating AuthorizedOfficer instances there)?

2, How do we suppose to list the available PartnerStaffMembers on the UI (on the admin this is handled by ChainedForeignKey I suppose)? Filter by partner on the PartnerStaffMembers list API?

3, How do we suppose to list the assigned AuthorizedOfficers on the Agreement detail? Extract name and ID from AuthorizedOfficer.officer and make a list on the serizlier?

Thanks

**Comment by ilcsik** [comment]
@ntrncic @robertavram 'list all partner-staff-members' removed  from task and from PR in https://github.com/unicef/etools/pull/252/commits/c68720a8743516ec36f92225cfd1e450ba91a5d0

Though I wonder If:

1, is create method needed on both /staff-members/ and partner/pk/staff-members
2, only on /staff-members/
3, only on partner/pk/staff-members (so we can remove /staff-members/ route)

**Comment by robertavram** [comment]
how it works is ok. if we're not adding anything to the django-rest default implementation there is no need to override

**Comment by ilcsik** [comment]
Ok removed in https://github.com/unicef/etools/pull/252/commits/893aa27778c55f7ac0d734a04e56bca4917ec80b

**Comment by caktus-philip** [comment]
This has mostly been satisfied. I assume that any outstanding needs (e.g. Get one staff member `/staff-members/pk`) are no longer relevant.
