### ISSUE TITLE
Take out ActivityInfo

### ISSUE THREAD

**Issue by robertavram** [unicef/etools#253]
remove the library and it's dependencies

**Comment by robertavram** [comment]
@ntrncic can you confirm that Lebanon CO is not still using this?

**Comment by ntrncic** [comment]
In addition write a script to dump out the data

**Comment by ilcsik** [comment]
Removal done in #300 

For dumping data do you think dumpdata command is feasible?

```
$ python EquiTrack/manage.py dumpdata activityinfo > a.json
```

**Comment by caktus-philip** [comment]
Confirmed that `activityinfo` is completely gone on the master branch
