### ISSUE TITLE
clean up bad migrations per schemas

### ISSUE THREAD

**Issue by robertavram** [unicef/etools#257]
we have inconsistency on migrations / business area. We need to fix this in prod..

**Comment by ntrncic** [comment]
the following code fixes business areas with bad reversion migrations. 

python manage.py migrate_schemas -s china reversion zero --fake
python manage.py migrate_schemas -s iraq reversion zero --fake
python manage.py migrate_schemas -s syria_xb reversion zero --fake
python manage.py migrate_schemas -s lebanon reversion zero --fake
python manage.py migrate_schemas -s south_sudan reversion zero --fake
python manage.py migrate_schemas -s turkey reversion zero --fake
python manage.py migrate_schemas -s sudan reversion zero --fake
python manage.py migrate_schemas -s new_york reversion zero --fake
python manage.py migrate_schemas -s syria reversion zero --fake
python manage.py migrate_schemas -s kenya reversion zero --fake
python manage.py migrate_schemas -s jordan reversion zero --fake
python manage.py migrate_schemas -s menaro reversion zero --fake
python manage.py migrate_schemas -s uat reversion zero --fake
python manage.py migrate_schemas -s sierra_leone reversion zero --fake
python manage.py migrate_schemas -s nepal reversion zero --fake
python manage.py migrate_schemas -s myanmar reversion zero --fake

python manage.py migrate_schemas -s china reversion
python manage.py migrate_schemas -s iraq reversion
python manage.py migrate_schemas -s syria_xb reversion
python manage.py migrate_schemas -s lebanon reversion
python manage.py migrate_schemas -s south_sudan reversion
python manage.py migrate_schemas -s turkey reversion
python manage.py migrate_schemas -s sudan reversion
python manage.py migrate_schemas -s new_york reversion
python manage.py migrate_schemas -s syria reversion
python manage.py migrate_schemas -s kenya reversion
python manage.py migrate_schemas -s jordan reversion
python manage.py migrate_schemas -s menaro reversion
python manage.py migrate_schemas -s uat reversion
python manage.py migrate_schemas -s sierra_leone reversion
python manage.py migrate_schemas -s nepal reversion
python manage.py migrate_schemas -s myanmar reversion

**Comment by ntrncic** [comment]
completed in production.
