### ISSUE TITLE
modify Result Api Endpoint 

### ISSUE THREAD

**Issue by robertavram** [unicef/etools#285]
one get endpoint that takes in and returns:

nothing in -> all outputs serialized with result-type as string (result_type.name) (not ids)

country_programme (values: year : String) -> all results that apply for that year's country programme

result_type in (string values [Output, Activity, Outcome]) -> all results filtered by that result type

filters can be combined.

**Comment by robertavram** [comment]
@ilcsik can you give this a shot? v2 of the current api endpoint to do this
https://etools-staging.unicef.org/api/reports/results/

**Comment by robertavram** [comment]
by default unless year is specified it will return only the results within the current country programme.

**Comment by caktus-philip** [comment]
Code has changed somewhat since the original PR but this need is satisfied
