### ISSUE TITLE
Intervention GET: result needs a currency property

### ISSUE THREAD

**Issue by adi130987** [unicef/etools#453]
We need a currency property set on intervention object to be used for planned budget.

**Comment by adi130987** [comment]
Intervention object contains `fr_number` which is an array of integer/string values. I need the details for each `fr_number` to be in a separate intervention object property called `fr_numbers_details`  that has this form:

```javascript
fr_numbers_details: {
    // some fr number
    "34523": { 
                'gran': 'European Commission/EC: SC150610',
                'wbs': '2490/A0/06/102/010',
                'fc_type': 'HACT:Reimbursement',
                'fc_reference': '0100193407-1',
                'agreement_amount': 106360.50,
                'commitment_amount': null,
                'expenditure_amount': 106360.50
    },
    // another fr number
    "7565": { 
                'gran': 'European Commission/EC: SC150610',
                'wbs': '2490/A0/06/102/010',
                'fc_type': 'HACT:Reimbursement',
                'fc_reference': '0100193407-1',
                'agreement_amount': 106360.50,
                'commitment_amount': null,
                'expenditure_amount': 106360.50
    }
}
```

**Comment by ilcsik** [comment]
@robertavram @ntrncic as per @adi130987 we also need this on POST and PATCH as well not just GET? Int that case, do we need to create new FundingCommitment objects, or just add/remove fr_numbers to/from "fr_numbers" property of Intervention?

**Comment by robertavram** [comment]
we don't need post and patch
it;'s readonly

**Comment by ilcsik** [comment]
Thanks. Regarding currency: it's included under planned_budget in each item. Let me know if we need more than this.

**Comment by adi130987** [comment]
@robertavram, @ilcsik ... the fr_numbers_details are readonly, but I still need them at least for patch. When you make updates to the intervention, the intervention object is updated with the response from the last update request. If I do not have details for those fr_numbers, no details will be displayed and on page refresh we might see those details ... and for sure it will be reported later as an issue.

**Comment by ilcsik** [comment]
@adi130987 So you'd rather need the full entity as a response after update, so that you always have the same data right? I think you have filed an issue regarding this already right?
