### ISSUE TITLE
File uploads fail for files over 1MB in size

### ISSUE THREAD

**Issue by jamescw** [unicef/etools#46]
The default of most proxies/web servers is around 1MB and most scanned PDFs are above this.
Suggest making this 10-20MB.

**Comment by robertavram** [comment]
just uploaded a larger file... can you verify in prod now?

**Comment by robertavram** [comment]
Tried to reproduce in production but I couldn't.

Closing - Please reopen if this is still an issue

**Comment by jamescw** [comment]
@achamseddine please verify

**Comment by achamseddine** [comment]
It's work

**Comment by jamescw** [comment]
@robertavram did you make a config tweak? in any case seems to be working so closing this. Thanks
