### ISSUE TITLE
Personalized dashboard endpoints

### ISSUE THREAD

**Issue by ntrncic** [unicef/etools#461]
Add filters for action points api
Add signed_by_unicef filter for interventions api

**Comment by ilcsik** [comment]
Action points api filter feature is already in place, can be used like:

/api/t2f/action_points/?f_person_responsible=<user_id>
/api/t2f/action_points/?f_assigned_by=<user_id>

**Comment by ilcsik** [comment]
my_partnerships filtering is done in https://github.com/unicef/etools/commit/ba7deacbe4730f96b67b7106c309c621246f230b

**Comment by ilcsik** [comment]
So this task is done.
