### ISSUE TITLE
504 timeout on large exports

### ISSUE THREAD

**Issue by jamescw** [unicef/etools#47]
504 request timeout happens on large exports of trips or partnerships

**Comment by robertavram** [comment]
Will Fix... it has to do with haproxy settings...

**Comment by jamescw** [comment]
yes and the file upload size is also a HAProxy setting

**Comment by cndesrosiers** [comment]
I have created a bug report for this in Pivotal (#127207665).

**Comment by robertavram** [comment]
This has been fixed. Haproxy settings extended and exports have been improved in performance slightly
