### ISSUE TITLE
validate csv exports

### ISSUE THREAD

**Issue by ewheeler** [unicef/etools#487]
while existing tests check that the exported column names are correct, it would be good to check that cells are not empty. 

ideally we'd check that dates are dates/numbers are numbers/urls are urls, but making sure that there are the correct number of rows of non-null cells would be a worthwhile check. then we at least know that we are not, for example, looping through the action points twice and including duplicates or filtering out some of them that should be present

might be overkill, but [goodtables-py](https://github.com/frictionlessdata/goodtables-py) can do some of these kinds of [basic sanity checks](http://goodtables.okfnlabs.org/api/run?report_type=grouped&data=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fgoodtables-web%2Fmaster%2Fexamples%2Finvalid-on-structure.csv&format=csv&report_limit=1000&row_limit=100000) out of the box (and can do more sophisticated type checks if you also supply a [table schema](http://specs.frictionlessdata.io/table-schema/)

**Comment by ilcsik** [comment]
@ewheeler I checked what you linked and did some improvements in here: https://github.com/unicef/etools/pull/559

My take on unit testing things like this is to be as explicit as a test could be without having abstraction layers like for e.g. a defined schema that need to be maintained and learnt "separately" from either the business logic or the unit testing logic so I think the 3rd party tools you linked might be an overkill.

For the same reason I was wondering what would be the best to achieve the same goal but remain explicit - and I think just checking the data in the CSV rows against the data objects is a fine enough solution here.

The only drawback is that it's more dirty with all the date conversion and duplicated serializer code sometimes, but apart from that, in this way we can make sure that we have the proper data, proper types of course, and proper serialization of the data itself, even in case of compound fields like an ArrayField represented as comma separated list in CSV.

So I tried to fill in as many field as I could in the export tests and checking them against the CSV result. To make some more improvement, it would be nice to identify some corner points like the action points you mentioned and write some more test and/or add more complex data.

What do you think?

**Comment by ewheeler** [comment]
@ilcsik thanks for following up on this. your improvements look good

i created this issue mostly to flag this issue for discussion and so that we work towards a good long term approach for testing exports.

definitely agree that maintaining a schema would be problematic for a number of reasons.

another approach would be to commit an example export file and then have a test case that creates a new export and diffs the existing export.
