### ISSUE TITLE
url to item in export serializers

### ISSUE THREAD

**Issue by ntrncic** [unicef/etools#504]

**Comment by robertavram** [comment]
https://github.com/unicef/etools-issues/issues/5

**Comment by robertavram** [comment]
closes:https://github.com/unicef/etools-issues/issues/5

**Comment by robertavram** [comment]
fixes:https://github.com/unicef/etools-issues/issues/5

**Comment by robertavram** [comment]
closes https://github.com/unicef/etools-issues/issues/5

**Comment by robertavram** [comment]
closes robertavram/etools-issues#5
