### ISSUE TITLE
Remove Hstore

### ISSUE THREAD

**Issue by robertavram** [unicef/etools#908]
- [x] Remove all [hstore fields](https://github.com/unicef/etools/pull/911)
- [x] Remove dependencies from old migrations
- [ ] Run migrations on prod
- [ ] Remove references in DB init scripts and other places

**Comment by caktus-philip** [comment]
@czue FYI, I did some HStore-related work in a previous PR. https://github.com/unicef/etools/pull/769

**Comment by czue** [comment]
nice thanks for the heads up! :raised_hands:

**Comment by czue** [comment]
@robertavram so it appears that there's [one place in the code still using `hstore`](https://github.com/unicef/etools/blob/develop/EquiTrack/partners/models.py#L1869-L1871) and there is a small amount of data in that field. You had mentioned on slack that we need to do a migration - would this be to migrate the data to a new place or just a schema migration to remove the field? If the former, where should the data go?

**Comment by robertavram** [comment]
@czue we can get rid of the data altogether.
