### ISSUE TITLE
API changes related to sync PMP -> PRP

### ISSUE THREAD

**Issue by dfryta** [unicef/etools#934]
List of PMP API changes required for PMP -> PRP sync:

- [x] (cory) Add support for passing in a workspace id (intervention id?) to get data for those workspaces. Currently it only sends data associated with the default workspace of the user.
- [x] add api results pagination (currently it returns all data in one response, might be an issue in case of large datasets like interventions),
- [x] add `update_date` field and possibility to filter by this field for partners, interventions (to get list of updated items from given date),
- [x] add `business_area_code` to workspace endpoint
- [x] add `id` to workspace endpoint
- [x] add workspace/country `code` to workspace endpoint
- [x] is `cso_type` or `partner_type` or `name` possible to be empty?
- [x] add `reporting_frequencies` to intervention endpoint: explicit: (start, end and due date).
- [x] are `start_date` or `end_date` possible to be empty (intervention endpoint)? Maybe empty since they are draft?
- [x] add `status` to intervention endpoint.
- [x] are `xxx_currency` fields required? Sometimes "funds_received": "1.01", "funds_received_currency": null. If null then assume USD?
- [x] add `id` to partner details `partner_org' in intervention endpoint. `id` is missing currently.
- [x] `unicef_vendor_number` is required but seems empty in some results (intervention endpoint). It should never be empty.
- [x] add `local_currency` details to **workspace endpoint** also (currently only `local_currency_id` is present. Eg. "local_currency_id": 132, is included... would be good to include local currency shortcode as well.
- [x] `https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=0` throws 500 error and so does https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=0600. This worked though: https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=2130
- [x] add `admin_level`, `location_id`, `country_code` to `locations` in `indicators` in intervention endpoint
- [x] add `agreement` to intervention endpoint
- [x] Expose disagg values in admin /admin/reports/disaggregation/

**Optional (future items)**
- [ ] add `structure_version` field to PD details (intervention endpoint) to track PD changes during time when structure changes?
- [ ] add `version` field to PD, for any changes to the PD (say title or attachment). This represents non-structural changes.

**Comment by robertavram** [comment]
@csabadenes can you pick this up?
leave the first checkbox out.. that will go in a separate task

 @dfryta @chachra answers:
Partners are not timestamped.
cso_type can be empty, partner_type I believe should never be empty..

**Comment by robertavram** [comment]
@czue do you have time to pick up the first checkbox?

**Comment by czue** [comment]
@robertavram sure. will ask for clarifications on the call today

**Comment by czue** [comment]
@robertavram sorry for dumb question but can you tell me what the class names (or URLs) are of intervention, partner, and workspace APIs? Just want to make sure I'm working in the right place

**Comment by chachra** [comment]
@czue 

/api/v2/partners/
/api/prp/v1/interventions
/api/v2/workspaces/

**Comment by czue** [comment]
Ok, I'm basically done with this (see referenced PRs above) but there are a few unresolved questions:

1. Do we want to paginate the partners API as well as interventions?
2. Partners don't currently have a modified date - do we want to add those fields to the model or is there another workaround for adding filtering?
3. Intervention date filtering only applies to the intervention itself and not any of its referenced models. Is this ok? If not it might be easier / more logical to add logic to modify the intervention modification date at write time, though am unsure.
4. I arbitrarily chose `[LimitOffsetPagination](http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination)` because I didn't see much of a convention for this. Any guidance?

@robertavram @chachra @dfryta

**Comment by dfryta** [comment]
> Do we want to paginate the partners API as well as interventions?

Depends of partners data size. We can skip for now.

>Partners don't currently have a modified date - do we want to add those fields to the model or is there another workaround for adding filtering?

We would like to know which partner data has change from last sync. We can skip for now I think. @chachra thoughts?

> Intervention date filtering only applies to the intervention itself and not any of its referenced models. Is this ok? If not it might be easier / more logical to add logic to modify the intervention modification date at write time, though am unsure.

I would like to get all new/updated interventions since last sync. @chachra opinions?

>I arbitrarily chose LimitOffsetPagination because I didn't see much of a convention for this. Any guidance?

That's OK for me.

@czue is it possible to push those changes to server?

**Comment by czue** [comment]
thanks for the quick responses @dfryta!

> @czue is it possible to push those changes to server?

I think this might have to wait for @robertavram to review/merge. also, what server are you using for testing?

**Comment by dfryta** [comment]
@czue https://etools-demo.unicef.org/api/prp/v1/interventions

**Comment by chachra** [comment]
v1 has nicer data (for our sync)... but what is v2 for then? https://etools-demo.unicef.org/api/v2/interventions/ @robertavram ?

**Comment by robertavram** [comment]
v2 is for our PMP consumption... prp/v1/ is for prp

**Comment by dfryta** [comment]
@robertavram is it possible to push all changes to demo server?

**Comment by robertavram** [comment]
@dfryta latest prp-integration branch changes have been pushed.. migrations running... will most likely be done in an hour or so

**Comment by dfryta** [comment]
Awesome! Thanks @robertavram!

**Comment by robertavram** [comment]
@dfryta We'll try to hash this out this week.. heads up on the reporting frequency... we implement "reporting periods"

**Comment by dfryta** [comment]
Thanks for info @robertavram!

**Comment by robertavram** [comment]
are xxx_currency fields required? 
> yes

 Sometimes "funds_received": "1.01",
> was buggy.. fixed... 

 "funds_received_currency": null.
>  that should not be null for active records.. do not assume USD... throw a fit..

`unicef_vendor_number` is required but seems empty in some results (intervention endpoint). 
> It should never be empty. - unless the partner org is added by hand... which in the current system should never be the case

`https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=0` throws 500 error and so does https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=0600. This worked though: https://etools-demo.unicef.org/api/prp/v1/interventions/?workspace=2130
> 0 is global.. avoid that one, 0600 was set on multiple workspaces... we'll fix the data.. otherwise should be good
